config:
  send_anonymous_usage_stats: false
  use_colors: true

tutorial:
  outputs:
    dev:
      type: spark
      method: thrift
      schema: default
      host: spark

      port: 10000
      user: hive

      connect_retries: 5
      connect_timeout: 5
      retry_all: true
  target: dev
