FROM bitnami/spark:3

ADD io.delta_delta-core_2.12-1.2.1.jar /opt/bitnami/spark/jars/.
ADD io.delta_delta-storage-1.2.1.jar /opt/bitnami/spark/jars/.
ADD org.codehaus.jackson_jackson-core-asl-1.9.13.jar /opt/bitnami/spark/jars/.
